namespace Tranquil.Schema;

public record CScenario_Position(float x, float y) : DotaPacket;
public record CScenarioGame_RoshanSpawner(int kill_count, int state, float cooldown, int killer_team) : DotaPacket;
public record CScenarioEnt_Courier(int team_number, int owner_player_id, float cooldown) : DotaPacket;
public record CScenarioEnt_NPC(CScenario_Position position, string unit_name, int team_number, float health_frac, bool unused5, bool unused6, bool unused7, bool unused8, bool unused9, string owning_camp, CScenario_Position owning_camp_position, bool unused12, bool unused13, bool unused14, bool unused15, bool unused16, bool unused17, bool unused18, bool unused19, string invade_goal) : DotaPacket;
public record CScenarioEnt_SpiritBear(int owner_id, int team_id) : DotaPacket;
public record CScenarioEnt_DroppedItem(CScenario_Position position) : DotaPacket;
public record CMsgDotaScenario(ulong lobby_id, CMsgDotaScenario.Game game, List<CMsgDotaScenario.Team> teams, List<CMsgDotaScenario.Hero> heroes, List<CMsgDotaScenario.Stock> stock, List<CMsgDotaScenario.Building> buildings, List<CMsgDotaScenario.Entity> entities, List<CMsgDotaScenario.Item> items, List<CMsgDotaScenario.Modifier> modifiers) : DotaPacket
{
    public record EntityRef(int player_id, int neutral_stash_id, int entity_idx, bool roshan, bool unused5, bool unused6, bool unused7, bool unused8, bool unused9, string ability_name);
    public record Game(ulong match_id, int game_mode, float clock_time, float internal_time, CScenarioGame_RoshanSpawner roshan);
    public record TeamNeutralItem(string name, bool consumed, int tier);
    public record Team(int team_number, List<CMsgDotaScenario.TeamNeutralItem> neutral_items, int hero_kills, int tower_kills, int barracks_kills, float glyph_cooldown, float radar_cooldown);
    public record HeroHeroInt(int player_id, int value);
    public record HeroHeroFloat(int player_id, float value);
    public record DamageStatsByType(int damage_type, int received_pre_reduction, int received_post_reduction, int outgoing_pre_reduction, int outgoing_post_reduction);
    public record HeroAbility(string name, int level);
    public record Hero(long SF2steam_id, int player_id, int team_id, string hero, int total_xp, int bkb_charges_used, int aeon_charges_used, int reliable_gold, int unreliable_gold, int total_earned_gold, int shared_gold, int hero_kill_gold, int creep_kill_gold, int neutral_kill_gold, int courier_gold, int bounty_gold, int roshan_gold, int building_gold, int other_gold, bool unused20, bool unused21, bool unused22, bool unused23, bool unused24, bool unused25, int income_gold, int ward_kill_gold, int ability_gold, int denies, int last_hits, int last_hit_streak, int last_hit_multikill, int nearby_creep_death_count, int claimed_deny_count, int claimed_miss_count, int miss_count, bool unused37, bool unused38, bool unused39, float buyback_cooldown_time, float buyback_gold_limit_time, bool unused42, bool unused43, float stun_duration, float healing, int tower_kills, int roshan_kills, int observer_wards_placed, int sentry_wards_placed, int creeps_stacked, int camps_stacked, int rune_pickups, int gold_spent_on_support, int hero_damage, int wards_purchased, int wards_destroyed, bool unused57, int gold_spent_on_consumables, int gold_spent_on_items, int gold_spent_on_buybacks, int gold_lost_to_death, int kills, int assists, int deaths, int kill_streak, bool unused66, bool unused67, int respawn_seconds, int last_buyback_time, bool unused70, bool first_blood_claimed, bool first_blood_given, int bounty_runes, int outposts_captured, CScenario_Position position, bool unused76, bool unused77, bool unused78, bool unused79, bool unused80, bool unused81, bool unused82, bool unused83, bool unused84, bool unused85, bool unused86, bool unused87, bool unused88, bool unused89, bool unused90, bool unused91, bool unused92, bool unused93, bool unused94, bool unused95, bool unused96, bool unused97, bool unused98, bool unused99, bool unused100, bool unused101, bool unused102, bool unused103, bool unused104, bool unused105, bool unused106, bool unused107, bool unused108, bool unused109, bool unused110, bool unused111, bool unused112, bool unused113, bool unused114, bool unused115, bool unused116, bool unused117, bool unused118, bool unused119, bool unused120, bool unused121, bool unused122, bool unused123, bool unused124, bool unused125, bool unused126, bool unused127, bool unused128, bool unused129, bool unused130, bool unused131, bool unused132, bool unused133, bool unused134, bool unused135, bool unused136, bool unused137, bool unused138, bool unused139, bool unused140, bool unused141, bool unused142, bool unused143, bool unused144, bool unused145, bool unused146, bool unused147, bool unused148, bool unused149, List<CMsgDotaScenario.HeroHeroInt> enemy_kills, List<CMsgDotaScenario.DamageStatsByType> damage_stats, List<CMsgDotaScenario.HeroAbility> abilities, uint hero_facet);
    public record Stock(string name, int team_number, int player_id, int current_stock, float cooldown, int bonus_stock);
    public record Building(string entity_name, string entity_class, int team_id, bool is_destroyed, float health_frac);
    public record Entity(CScenarioEnt_Courier courier, CScenarioEnt_NPC npc, CScenarioEnt_SpiritBear spirit_bear, CScenarioEnt_DroppedItem dropped_item);
    public record Item(string name, CMsgDotaScenario.EntityRef location, int owner_id, int item_slot, int neutral_drop_team, int charges, int secondary_charges, float lifetime, int stored_rune_type);
    public record Modifier(string name, CMsgDotaScenario.EntityRef parent, CMsgDotaScenario.EntityRef caster, CMsgDotaScenario.EntityRef ability, float duration, float lifetime_remaining, int stack_count, bool create_even_if_existing, bool create_without_caster, bool create_without_ability, bool unused11, bool unused12, bool unused13, bool unused14, bool unused15, bool unused16, bool unused17, bool unused18, bool unused19, bool unused20, bool unused21, bool unused22, bool unused23, bool unused24, bool unused25, bool unused26, bool unused27, bool unused28, bool unused29, bool unused30, bool unused31, bool unused32, bool unused33, bool unused34, bool unused35, bool unused36, bool unused37, bool unused38, bool unused39, bool unused40, bool unused41, bool unused42, bool unused43, bool unused44, bool unused45, bool unused46, bool unused47, bool unused48, bool unused49, bool unused50, bool unused51, bool unused52, bool unused53, bool unused54, bool unused55, bool unused56, bool unused57, bool unused58, bool unused59, bool unused60, bool unused61, bool unused62, bool unused63, bool unused64, bool unused65, bool unused66, bool unused67, bool unused68, bool unused69, bool unused70, bool unused71, bool unused72, bool unused73, bool unused74, bool unused75, bool unused76, bool unused77, bool unused78, bool unused79, bool unused80, bool unused81, bool unused82, bool unused83, bool unused84, bool unused85, bool unused86, bool unused87, bool unused88, bool unused89, bool unused90, bool unused91, bool unused92, bool unused93, bool unused94, bool unused95, bool unused96, bool unused97, bool unused98, bool unused99, int moonshard_consumed_bonus, int moonshard_consumed_bonus_night_vision, bool unused102, bool unused103, bool unused104, bool unused105, bool unused106, bool unused107, bool unused108, bool unused109, int wardtruesight_range, bool unused111, bool unused112, bool unused113, bool unused114, bool unused115, bool unused116, bool unused117, bool unused118, bool unused119, int ultimate_scepter_consumed_alchemist_bonus_all_stats, int ultimate_scepter_consumed_alchemist_bonus_health, int ultimate_scepter_consumed_alchemist_bonus_mana);
}
