using Tranquil.Schema.Dota;

namespace Tranquil.Schema;

public record CGameNetworkingUI_GlobalState : DotaPacket;
public record CGameNetworkingUI_ConnectionState(string connection_key, uint appid, int SF1connection_id_local, string identity_local, string identity_remote, bool unused6, bool unused7, bool unused8, bool unused9, uint connection_state, bool unused11, uint start_time, uint close_time, uint close_reason, string close_message, string status_loc_token, bool unused17, bool unused18, bool unused19, uint transport_kind, string sdrpopid_local, string sdrpopid_remote, string address_remote, CMsgSteamDatagramP2PRoutingSummary p2p_routing, uint ping_interior, uint ping_remote_front, uint ping_default_internet_route, bool unused28, bool unused29, CMsgSteamDatagramConnectionQuality e2e_quality_local, CMsgSteamDatagramConnectionQuality e2e_quality_remote, ulong e2e_quality_remote_instantaneous_time, ulong e2e_quality_remote_lifetime_time, bool unused34, bool unused35, bool unused36, bool unused37, bool unused38, bool unused39, CMsgSteamDatagramConnectionQuality front_quality_local, CMsgSteamDatagramConnectionQuality front_quality_remote, ulong front_quality_remote_instantaneous_time, ulong front_quality_remote_lifetime_time) : DotaPacket;
public record CGameNetworkingUI_Message(List<CGameNetworkingUI_ConnectionState> connection_state) : DotaPacket;
public record CGameNetworkingUI_ConnectionSummary(uint transport_kind, string sdrpop_local, string sdrpop_remote, uint ping_ms, float packet_loss, uint ping_default_internet_route, bool ip_was_shared, uint connection_state) : DotaPacket;
public record CGameNetworkingUI_AppSummary(uint appid, bool unused2, bool unused3, bool unused4, bool unused5, bool unused6, bool unused7, bool unused8, bool unused9, bool ip_was_shared_with_friend, bool ip_was_shared_with_nonfriend, bool unused12, bool unused13, bool unused14, bool unused15, bool unused16, bool unused17, bool unused18, bool unused19, uint active_connections, bool unused21, bool unused22, bool unused23, bool unused24, bool unused25, bool unused26, bool unused27, bool unused28, bool unused29, CGameNetworkingUI_ConnectionSummary main_cxn) : DotaPacket;
