using Tranquil.Schema.Dota;

namespace Tranquil.Schema;

public record CMsgSteamDatagramRelayAuthTicket(int SF1time_expiry, long SF2legacy_authorized_steam_id, int SF1authorized_public_ip, long SF2legacy_gameserver_steam_id, bool unused5, bool unused6, uint app_id, List<CMsgSteamDatagramRelayAuthTicket.ExtraField> extra_fields, int SF1legacy_gameserver_pop_id, uint virtual_port, byte[] gameserver_address, byte[] legacy_authorized_client_identity_binary, byte[] legacy_gameserver_identity_binary, string authorized_client_identity_string, string gameserver_identity_string) : DotaPacket
{
    public record ExtraField(string name, string string_value, long SS2int64_value, bool unused4, long SF2fixed64_value);
}
public record CMsgSteamDatagramSignedRelayAuthTicket(long SF2reserved_do_not_use, long SF2key_id, byte[] ticket, byte[] signature, List<CMsgSteamDatagramCertificateSigned> certs) : DotaPacket;
public record CMsgSteamDatagramCachedCredentialsForApp(byte[] private_key, byte[] cert, List<byte[]> relay_tickets) : DotaPacket;
public record CMsgSteamDatagramGameCoordinatorServerLogin(uint time_generated, uint appid, byte[] routing, byte[] appdata, byte[] legacy_identity_binary, string identity_string, bool unused7, bool unused8, bool unused9, bool unused10, bool unused11, bool unused12, bool unused13, bool unused14, bool unused15, bool unused16, bool unused17, bool unused18, bool unused19, bool unused20, bool unused21, bool unused22, bool unused23, bool unused24, bool unused25, bool unused26, bool unused27, bool unused28, bool unused29, bool unused30, bool unused31, bool unused32, bool unused33, bool unused34, bool unused35, bool unused36, bool unused37, bool unused38, bool unused39, bool unused40, bool unused41, bool unused42, bool unused43, bool unused44, bool unused45, bool unused46, bool unused47, bool unused48, bool unused49, bool unused50, bool unused51, bool unused52, bool unused53, bool unused54, bool unused55, bool unused56, bool unused57, bool unused58, bool unused59, bool unused60, bool unused61, bool unused62, bool unused63, bool unused64, bool unused65, bool unused66, bool unused67, bool unused68, bool unused69, bool unused70, bool unused71, bool unused72, bool unused73, bool unused74, bool unused75, bool unused76, bool unused77, bool unused78, bool unused79, bool unused80, bool unused81, bool unused82, bool unused83, bool unused84, bool unused85, bool unused86, bool unused87, bool unused88, bool unused89, bool unused90, bool unused91, bool unused92, bool unused93, bool unused94, bool unused95, bool unused96, bool unused97, bool unused98, long SF2dummy_steam_id) : DotaPacket;
public record CMsgSteamDatagramSignedGameCoordinatorServerLogin(CMsgSteamDatagramCertificateSigned cert, byte[] login, byte[] signature) : DotaPacket;
public record CMsgSteamDatagramHostedServerAddressPlaintext(int SF1ipv4, byte[] ipv6, uint port, long SF2routing_secret, uint protocol_version) : DotaPacket;
