using Tranquil.Schema.Dota;

namespace Tranquil.Schema;

public record CMsgClientHeartBeat : DotaPacket;
public record CMsgClientServerTimestampRequest(ulong client_request_timestamp) : DotaPacket;
public record CMsgClientServerTimestampResponse(ulong client_request_timestamp, ulong server_timestamp_ms) : DotaPacket;
public record CMsgClientSecret(uint version, uint appid, uint deviceid, long SF2nonce, byte[] hmac) : DotaPacket;
public record CMsgClientLogon(uint protocol_version, uint deprecated_obfustucated_private_ip, uint cell_id, uint last_session_id, uint client_package_version, string client_language, uint client_os_type, bool should_remember_password, string wine_version, uint deprecated_10, CMsgIPAddress obfuscated_private_ip, bool unused12, bool unused13, bool unused14, bool unused15, bool unused16, bool unused17, bool unused18, bool unused19, uint deprecated_public_ip, uint qos_level, long SF2client_supplied_steam_id, CMsgIPAddress public_ip, bool unused24, bool unused25, bool unused26, bool unused27, bool unused28, bool unused29, byte[] machine_id, uint launcher_type, uint ui_mode, uint chat_mode, bool unused34, bool unused35, bool unused36, bool unused37, bool unused38, bool unused39, bool unused40, byte[] steam2_auth_ticket, string email_address, int SF1rtime32_account_creation, bool unused44, bool unused45, bool unused46, bool unused47, bool unused48, bool unused49, string account_name, string password, string game_server_token, bool unused53, bool unused54, bool unused55, bool unused56, bool unused57, bool unused58, bool unused59, string login_key, bool unused61, bool unused62, bool unused63, bool unused64, bool unused65, bool unused66, bool unused67, bool unused68, bool unused69, bool was_converted_deprecated_msg, bool unused71, bool unused72, bool unused73, bool unused74, bool unused75, bool unused76, bool unused77, bool unused78, bool unused79, string anon_user_target_account_name, long SF2resolved_user_steam_id, int eresult_sentryfile, byte[] sha_sentryfile, string auth_code, int otp_type, uint otp_value, string otp_identifier, bool steam2_ticket_request, bool unused89, byte[] sony_psn_ticket, string sony_psn_service_id, bool create_new_psn_linked_account_if_needed, string sony_psn_name, int game_server_app_id, bool steamguard_dont_remember_computer, string machine_name, string machine_name_userchosen, string country_override, bool is_steam_box, ulong client_instance_id, string two_factor_code, bool supports_rate_limit_response, string web_logon_nonce, int priority_reason, CMsgClientSecret embedded_client_secret) : DotaPacket;
public record CMsgClientLogonResponse(int eresult, int out_of_game_heartbeat_seconds, int in_game_heartbeat_seconds, uint deprecated_public_ip, int SF1rtime32_server_time, uint account_flags, uint cell_id, string email_domain, byte[] steam2_ticket, int eresult_extended, string webapi_authenticate_user_nonce, uint cell_id_ping_threshold, bool use_pics, string vanity_url, CMsgIPAddress public_ip, bool unused16, bool unused17, bool unused18, bool unused19, long SF2client_supplied_steamid, string ip_country_code, byte[] parental_settings, byte[] parental_setting_signature, int count_loginfailures_to_migrate, int count_disconnects_to_migrate, int ogs_data_report_time_window, ulong client_instance_id, bool force_client_update_check) : DotaPacket;
public record CMsgClientRequestWebAPIAuthenticateUserNonce(int token_type) : DotaPacket;
public record CMsgClientRequestWebAPIAuthenticateUserNonceResponse(int eresult, bool unused2, int token_type, string webapi_authenticate_user_nonce) : DotaPacket;
public record CMsgClientLogOff : DotaPacket;
public record CMsgClientLoggedOff(int eresult) : DotaPacket;
public record CMsgClientNewLoginKey(uint unique_id, string login_key) : DotaPacket;
public record CMsgClientNewLoginKeyAccepted(uint unique_id) : DotaPacket;
public record CMsgClientAccountInfo(string persona_name, string ip_country, bool unused3, bool unused4, int count_authed_computers, bool unused6, uint account_flags, ulong facebook_id, string facebook_name, bool unused10, bool unused11, bool unused12, bool unused13, bool steamguard_notify_newmachines, string steamguard_machine_name_user_chosen, bool is_phone_verified, uint two_factor_state, bool is_phone_identifying, bool is_phone_needing_reverify) : DotaPacket;
public record CMsgClientChallengeRequest(long SF2steamid) : DotaPacket;
public record CMsgClientChallengeResponse(long SF2challenge) : DotaPacket;
